### ISSUE TITLE
Number of bills

### ISSUE THREAD

**Issue by zzolo** [MinnPost/legislature-tracker#9]
Currently there is less than 50 bills tracked.  This could easily run up some performance limits at some point.  There are methods of caching and only getting data as needed.

There is data pulled from Google Spreadsheets 

There are two main points where data from Open States is brought in:
- Categories page calles the search API on the bills which gets basic data on the bill.  This also populates the recent bill category.
  *Individual Category gets the bill details of each bill in the category.

At the least, there should be a suggested amount of total bills and number of bills in a category.

**Comment by jeremybmerrill** [comment]
One way to implement this would be to have a `maxBills` option in `defaultOptions` and only load the first `maxBills` eBills (and LT.log an explanatory msg if the number of bills in the spreadsheet is > maxBills). Then, rather than unknowingly ending up with a malperformant app, they'll have to explicitly raise the number of bills to be displayed.)

Could do this for categories too. (E.g. we support up to 8 categories, modifying the styles for >8 is up to you.)
